apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  depends_on:
     - db-mysql
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
  - name: "4040"
    port: 4040
    targetPort: 80
  selector:
    io.kompose.service: app
  externalIPs: 
        - 192.168.4.50
status:
  loadBalancer: {}
