apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  depends_on:
    - db-mysql
  labels:
    io.kompose.service: app
  name: app
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: test
    - name: DB_DATABASE
      value: mysql
    - name: DB_HOST
      value: db-mysql
    - name: DB_PASSWORD
      value: test
    - name: DB_PORT
      value: "3306"
    - name: DB_USERNAME
      value: test
    image: edashdondog/readtextwritemysql:latest
    name: app
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 100m
        memory: "52428800"
  restartPolicy: OnFailure
status: {}
