apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: new
  name: new
spec:
  ports:
  - name: "4040"
    port: 4040
    targetPort: 80
  selector:
    io.kompose.service: new
status:
  loadBalancer: {}
